name: Move dummy.txt to temp directory

on:
  push:
    branches: [ main ]

jobs:
  move-dummy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Move dummy.txt to temp directory
      run: |
        mkdir temp
        mv dummy.txt temp/
        git add temp/
        git commit -m "Move dummy.txt to temp directory"
        git push origin main
